#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Adaptive.ReactiveTrader.Client.Android.Resource", IsApplication=true)]

namespace Adaptive.ReactiveTrader.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dotted = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notional_background_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notional_background_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notional_background_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notional_textcolor_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pricebutton_background_normal = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pricebutton_background_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pricebutton_background_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int pricebutton_foreground_selector = 2130837514;
			
			// aapt resource value: 0x7f02000e
			public const int red = 2130837518;
			
			// aapt resource value: 0x7f02000b
			public const int spottile_background_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int spottile_background_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int spottile_background_selector = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int BlotterRowCurrencyPairTextView = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int BlotterRowDirectionTextView = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int BlotterRowNotionalTextView = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int BlotterRowSpotRateTextView = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int BlotterRowStatusTextView = 2131099653;
			
			// aapt resource value: 0x7f060000
			public const int BlotterRowTradeDateTextView = 2131099648;
			
			// aapt resource value: 0x7f060008
			public const int BlotterRowTradeIdTextView = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int BlotterRowTraderNameTextView = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int BlotterRowValueDateTextView = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int BlotterRowsRecyclerView = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int PriceButtonBigFiguresTextView = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int PriceButtonDirectionTextView = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int PriceButtonPipsTextView = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int PriceButtonTenthOfPipTextView = 2131099661;
			
			// aapt resource value: 0x7f060015
			public const int SpotTileAskPriceButton = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int SpotTileBidPriceButton = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int SpotTileCurrencyPairTextView = 2131099663;
			
			// aapt resource value: 0x7f060016
			public const int SpotTileDealtCurrencyTextView = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int SpotTileDownArrow = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int SpotTileNotionalEditText = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int SpotTileSpotDateTextView = 2131099672;
			
			// aapt resource value: 0x7f060011
			public const int SpotTileSpreadLayout = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int SpotTileSpreadTextView = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int SpotTileUpArrow = 2131099666;
			
			// aapt resource value: 0x7f06000e
			public const int SpotTilesRecyclerView = 2131099662;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlotterRowView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BlotterView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PriceButton = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ShellView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SpotTileView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
